const images = {
  menu_burger: require('../../assets/icons/outline_menu_white_48dp.png'),

  ellipse_bar: require('../../assets/icons/icon_ellipse_bar.png'),
  favourite: require('../../assets/icons/icon_favourite.png'),
  gps: require('../../assets/icons/icon_gps.png'),
  location: require('../../assets/icons/icon_location.png'),
  logo: require('../../assets/images/logo.png'),
  sportunity: require('../../assets/icons/sportunity.png'),
  organize: require('../../assets/icons/baseline_add_circle_outline_white_48dp.png'),
  red_user: require('../../assets/icons/icon_red_user.png'),
  share: require('../../assets/icons/icon_share.png'),
  shoes: require('../../assets/icons/icon_shoes.png'),
  sportunity_group: require('../../assets/icons/sportunity_group.png'),
  refresh: require('../../assets/icons/refresh.png'),

  stadium: require('../../assets/icons/img_stadium.png'),
    // TODO: this is temporal, this should not be an statical
    // image, but an url to
    // an external resource.

  tenis: require('../../assets/icons/icon_tenis.png'),
  w_share: require('../../assets/icons/icon_w_share.png'),
  y_heart: require('../../assets/icons/icon_y_heart.png'),
  facourite: require('../../assets/icons/icon_favourite.png'),
  key: require('../../assets/icons/icon_key.png'),
  profile_photo: require('../../assets/icons/icon_profile_photo.png'),
  master_card: require('../../assets/icons/master_card.png'),
  accepted_cards: require('../../assets/icons/accepted_cards.png'),
  pay_pall: require('../../assets/icons/paypal_text.png'),
  close_x: require('../../assets/icons/icon_close_x.png'),
  down_arrow: require('../../assets/icons/icon_down_arrow.png'),
  up_arrow: require('../../assets/icons/icon_up_arrow.png'),
  pen: require('../../assets/icons/icon_pen.png'),
  search: require('../../assets/icons/icon_search.png'),
  search_blue: require('../../assets/icons/search.png'),
  search_black: require('../../assets/icons/search_black.png'),
  right_arrow_blue: require('../../assets/icons/right-arrow-blue.png'),
  activities: require('../../assets/icons/icon_activities.png'),
  info: require('../../assets/icons/icon_info.png'),
  list: require('../../assets/icons/icon_list.png'),
  comments: require('../../assets/icons/icon_comments.png'),
  bell: require('../../assets/icons/baseline_notifications_active_white_48dp.png'),
  circle: require('../../assets/icons/icon_circle.png'),
  circle2: require('../../assets/icons/cercle-01.png'),
  stars4: require('../../assets/icons/icon_stars4.png'),
  block: require('../../assets/icons/icon_block.png'),
  link: require('../../assets/icons/icon_link.png'),
  cog: require('../../assets/icons/icon_cog.png'),
  roundedPlus: require('../../assets/icons/icon_plus.png'),
  logout: require('../../assets/icons/logout-01-01.png'),
  myProfile: require('../../assets/icons/profil-01-01.png'),
  settings: require('../../assets/icons/settings-01.png'),
  members: require('../../assets/icons/family-01.png'),
  wallet: require('../../assets/icons/wallet.png'),
  add_circle: require('../../assets/icons/round_add_circle_outline_black_48dp.png'),
  error_black: require('../../assets/icons/round_error_outline_black_48dp.png'),

  tennis: require('../../assets/icons/icon_tennis.png'),
  jogging: require('../../assets/icons/icon_jogging.png'),
  basketball: require('../../assets/icons/icon_basketball.png'),
  filter: require('../../assets/icons/baseline_tune_white_48dp.png'),
  expand_arrow: require('../../assets/images/24x15_expand.png'),
  close: require('../../assets/images/31x30_close.png'),
  close_white: require('../../assets/icons/close_white.png'),
  right_arrow: require('../../assets/images/36x40_right_arrow.png'),
  circleLarge: require('../../assets/images/circle.png'),

  calendarCheck: require('../../assets/icons/calendar_check_icon.png'),
  calendarAdd: require('../../assets/icons/add_calendar_icon.png'),
  check: require('../../assets/icons/check_icon.png'),
  checkWhite: require('../../assets/icons/check_white.png'),
  commentsIcon: require('../../assets/icons/comments_icon.png'),
  calendar: require('../../assets/icons/icon_calendar.png'),
  infoIcon: require('../../assets/icons/info_icon.png'),
  question: require('../../assets/icons/question_icon.png'),
  timeIcon: require('../../assets/icons/time_icon.png'),
  stats: require('../../assets/icons/icon_stats.png'),
  plus: require('../../assets/icons/plus.png'),
  fileText: require('../../assets/icons/file-text.png'),

  neverLoggedIn: require('../../assets/icons/icon_never_loggedin.png'),

  /*tutorialBrowseEN: require('../../assets/images/Explore-EN.png'),
  tutorialFilterEN: require('../../assets/images/Filter-EN.png'),
  tutorialMySportunitiesEN: require('../../assets/images/My-sportunities-EN.png'),
  tutorialOrganizationEN: require('../../assets/images/Organization-EN.png'),
  tutorialCirclesEN: require('../../assets/images/Circles-EN.png'),
  tutorialBrowseFR: require('../../assets/images/Explore-FR.png'),
  tutorialFilterFR: require('../../assets/images/Filter-FR.png'),
  tutorialMySportunitiesFR: require('../../assets/images/My-sportunities-FR.png'),
  tutorialOrganizationFR: require('../../assets/images/Organization-FR.png'),
  tutorialCirclesFR: require('../../assets/images/Circles-FR.png'),*/
  tutorialCalendarSyncEN: require('../../assets/images/Calendar-Sync-EN.png'),
  tutorialCalendarSyncFR: require('../../assets/images/Calendar-Sync-FR.png'),

  tutorial1_EN: require('../../assets/images/Tutoriel-EN-1.png'),
  tutorial1_FR: require('../../assets/images/Tutoriel-FR-1.png'),
  tutorial2_EN: require('../../assets/images/Tutoriel-EN-2.png'),
  tutorial2_FR: require('../../assets/images/Tutoriel-FR-2.png'),
  tutorial3_EN: require('../../assets/images/Tutoriel-EN-3.png'),
  tutorial3_FR: require('../../assets/images/Tutoriel-FR-3.png'),

  tutorialSwipeRight: require('../../assets/images/tutorial/swipe-right.png'),
  tutorialSwipeLeft: require('../../assets/images/tutorial/swipe-left.png'),

  carPooling: require('../../assets/images/CarPooling.png'),
  coOrganizers: require('../../assets/images/coOrganizers.png'),
  infrastructure: require('../../assets/images/infrastructure.png'),
  compositions: require('../../assets/icons/compositions.png'),
  circle_fees: require('../../assets/icons/coti_club-01.png'),
  circle_forms: require('../../assets/icons/form_club-01.png'),

  statisitics: require('../../assets/images/statistic_black.png'),
  addGroup: require('../../assets/icons/add_group_icon.png'),
  privateGroup: require('../../assets/icons/private_group_icon.png'),
  publicGroup: require('../../assets/icons/public_group_icon.png'),
  validDocument: require('../../assets/icons/valid-document.png'),
  cashRightArrow: require('../../assets/icons/cash_right_arrow.png'),
  cashIn: require('../../assets/icons/cash_in.png'),
  cashOut: require('../../assets/icons/cash_out.png'),
};

export default images;
