export const changeSportunityFilterKind = // eslint-disable-line import/prefer-default-export
  'SPORTUNITY_CHANGE_SPORTUNITY_FILTER_KIND';
export const createActivity = // eslint-disable-line import/prefer-default-export
  'SPORTUNITY_CREATE_ACTIVITY';

// Ajax request
export const FETCHING_DATA = 'FETCHING_DATA';

// Login
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// Drawer
export const VERIFY_AUTH = 'VERIFY_AUTH';
export const IS_LOGGED_IN = 'IS_LOGGED_IN';

// Create Profile

export const CREATING_PROFILE = 'CREATING_PROFILE';
export const CREATING_SUB_ACCOUNT = 'CREATING_SUB_ACCOUNT';
export const UPDATE_AVATAR = 'UPDATE_AVATAR';
export const UPDATE_PSEUDO = 'UPDATE_PSEUDO';
export const UPDATE_NAME = 'UPDATE_NAME';
export const UPDATE_PHONE = 'UPDATE_PHONE';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const UPDATE_DESCRIPTION = 'UPDATE_DESCRIPTION';
export const UPDATE_BIRTHDAY = 'UPDATE_BIRTHDAY';
export const UPDATE_LANGUAGES = 'UPDATE_LANGUAGES';
export const UPDATE_SPORTS = 'UPDATE_SPORTS';
export const UPDATE_REPORT_TEXT = 'UPDATE_REPORT_TEXT';
export const VALIDATE_CREATE_PROFILE_INPUTS = 'VALIDATE_CREATE_PROFILE_INPUTS';
export const RESET_PROFILE_CREATION = 'RESET_PROFILE_CREATION';

// Profile

export const UPDATE_FROM = 'UPDATE_FROM';
export const UPDATE_POPUP_COMPLETE_PROFILE_IS_DISPLAYED = 'UPDATE_POPUP_COMPLETE_PROFILE_IS_DISPLAYED';
export const UPDATE_STEPS_COMPLETED = 'UPDATE_STEPS_COMPLETED';
export const UPDATE_STEPS_PERCENTAGE = 'UPDATE_STEPS_PERCENTAGE';
export const UPDATE_NEXT_STEP_TO_DO = 'UPDATE_NEXT_STEP_TO_DO';
export const RESET_TUTORIAL_STEPS = 'RESET_TUTORIAL_STEPS';
export const TOGGLE_PROGRESS_BAR_DISPLAY = 'TOGGLE_PROGRESS_BAR_DISPLAY';
export const GIVE_PERMISSION_TO_HIDE_PROGRESS = 'GIVE_PERMISSION_TO_HIDE_PROGRESS';

// Sport

export const UPDATE_SEARCHTEXT = 'UPDATE_SEARCHTEXT';

// Signup

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

// NEW ACTIVITY

export const IS_DATE_MODAL_VISIBLE = 'IS_DATE_MODAL_VISIBLE';
export const IS_LEVEL_MODAL_VISIBLE = 'IS_LEVEL_MODAL_VISIBLE';
export const IS_PRICE_MODAL_VISIBLE = 'IS_PRICE_MODAL_VISIBLE';
export const IS_NUMBER_MODAL_VISIBLE = 'IS_NUMBER_MODAL_VISIBLE';
export const IS_PLACE_MODAL_VISIBLE = 'IS_PLACE_MODAL_VISIBLE';
export const IS_PLACE_OR_VENUE_MODAL_VISIBLE = 'IS_PLACE_OR_VENUE_MODAL_VISIBLE';
export const IS_VENUE_MODAL_VISIBLE = 'IS_VENUE_MODAL_VISIBLE';
export const IS_CO_ORGANIZER_MODAL_VISIBLE = 'IS_CO_ORGANIZER_MODAL_VISIBLE';
export const IS_RESTRICTIONS_MODAL_VISIBLE = 'IS_RESTRICTIONS_MODAL_VISIBLE';
export const IS_SPORT_MODAL_VISIBLE = 'IS_SPORT_MODAL_VISIBLE';
// New Activity Sport
export const UPDATE_ACTIVITY_SPORT = 'UPDATE_ACTIVITY_SPORT';
// New activity Title & Description
export const UPDATE_SEARCH_SPORT_TEXT = 'UPDATE_SEARCH_SPORT_TEXT';
export const UPDATE_ACTIVITY_TITLE = 'UPDATE_ACTIVITY_TITLE';
export const UPDATE_ACTIVITY_DESCRIPTION = 'UPDATE_ACTIVITY_DESCRIPTION';
// New Activity Level
export const UPDATE_ALL_LEVELS = 'UPDATE_ALL_LEVELS';
export const UPDATE_BEGINNER_LEVEL = 'UPDATE_BEGINNER_LEVEL';
export const UPDATE_INTERMEDIATE_LEVEL = 'UPDATE_INTERMEDIATE_LEVEL';
export const UPDATE_ADVANCED_LEVEL = 'UPDATE_ADVANCED_LEVEL';
export const UPDATE_PRO_LEVEL = 'UPDATE_PRO_LEVEL';
export const UPDATE_LEVEL_RANGE = 'UPDATE_LEVEL_RANGE';
export const UPDATE_LEVEL_MIN_SLIDER = 'UPDATE_LEVEL_MIN_SLIDER';
export const UPDATE_LEVEL_MAX_SLIDER = 'UPDATE_LEVEL_MAX_SLIDER';
export const UPDATE_MULTIPLE_LEVELS = 'UPDATE_MULTIPLE_LEVELS';
// New Activity date
export const UPDATE_NEW_ACTIVITY_DATE = 'UPDATE_NEW_ACTIVITY_DATE';
export const UPDATE_NEW_ACTIVITY_END_DATE = 'UPDATE_NEW_ACTIVITY_END_DATE';
export const UPDATE_FROM_HOUR = 'UPDATE_FROM_HOUR';
export const UPDATE_FROM_MINUTE = 'UPDATE_FROM_MINUTE';
export const UPDATE_TO_HOUR = 'UPDATE_TO_HOUR';
export const UPDATE_TO_MINUTE = 'UPDATE_TO_MINUTE';
export const UPDATE_REPEAT_SWITCH = 'UPDATE_REPEAT_SWITCH';
export const UPDATE_REPEAT_VALUE = 'UPDATE_REPEAT_VALUE';
export const UPDATE_IS_DATE_UPDATABLE = 'UPDATE_IS_DATE_UPDATABLE';
export const RESET_DATE = 'RESET_DATE';
// New Activity Advanced Settings
export const UPDATE_SEX_RESTRICTION = 'UPDATE_SEX_RESTRICTION';
export const UPDATE_AGE_RESTRICTION = 'UPDATE_AGE_RESTRICTION';
// New Activity Sportunity Type and game information
export const UPDATE_SPORTUNITY_TYPE = 'UPDATE_SPORTUNITY_TYPE';
export const UPDATE_SPORTUNITY_TYPE_STRING = 'UPDATE_SPORTUNITY_TYPE_STRING';
export const UPDATE_SPORTUNITY_OPPONENT = 'UPDATE_SPORTUNITY_OPPONENT';
export const UPDATE_SPORTUNITY_CIRCLE_OF_OPPONENTS = 'UPDATE_SPORTUNITY_CIRCLE_OF_OPPONENTS';
export const UPDATE_SPORTUNITY_OPEN_MATCH = 'UPDATE_SPORTUNITY_OPEN_MATCH';
export const UPDATE_SPORTUNITY_UNKNWON_OPPONENT = 'UPDATE_SPORTUNITY_UNKNWON_OPPONENT';
// New Activity place
export const UPDATE_PLACE_SWITCH = 'UPDATE_PLACE_SWITCH';
export const UPDATE_SEARCH_PLACE_TEXT = 'UPDATE_SEARCH_PLACE_TEXT';
export const UPDATE_ACTIVITY_PLACE = 'UPDATE_ACTIVITY_PLACE';
export const UPDATE_ACTIVITY_ADDRESS = 'UPDATE_ACTIVITY_ADDRESS';
export const UPDATE_ACTIVITY_VENUE = 'UPDATE_ACTIVITY_VENUE';
export const UPDATE_ACTIVITY_INFRASTRUCTURE = 'UPDATE_ACTIVITY_INFRASTRUCTURE';
export const UPDATE_ACTIVITY_SLOT = 'UPDATE_ACTIVITY_SLOT';
// New Activity number
export const UPDATE_MINIMUM_NUMBER = 'UPDATE_MINIMUM_NUMBER';
export const UPDATE_MAXIMUM_NUMBER = 'UPDATE_MAXIMUM_NUMBER';
export const UPDATE_EXACTLY_NUMBER = 'UPDATE_EXACTLY_NUMBER';
export const UPDATE_EXACTLY_SWITCH = 'UPDATE_EXACTLY_SWITCH';
export const UPDATE_HIDE_PARTICIPANT_SWITCH = 'UPDATE_HIDE_PARTICIPANT_SWITCH';
export const UPDATE_NOTIFY_PROPLE_SWITCH = 'UPDATE_NOTIFY_PROPLE_SWITCH';
export const ADD_USER_AS_PARTICIPANT ='ADD_USER_AS_PARTICIPANT';
// New Activity Price
export const UPDATE_FREE_SWITCH = 'UPDATE_FREE_SWITCH';
export const UPDATE_ORGANIZER_CONTRIBUTION = 'UPDATE_ORGANIZER_CONTRIBUTION';
export const UPDATE_VENUE_COST = 'UPDATE_VENUE_COST';
export const UPDATE_PRICE_PER_PARTICIPANT = 'UPDATE_PRICE_PER_PARTICIPANT';
export const UPDATE_MINIMUM_REVENUE = 'UPDATE_MINIMUM_REVENUE';
export const UPDATE_MAXIMUM_REVENUE = 'UPDATE_MAXIMUM_REVENUE';
export const IS_PRICE_UPDATABLE = 'IS_PRICE_UPDATABLE';
// Private
export const UPDATE_PRIVATE_ACTIVITY = 'UPDATE_PRIVATE_ACTIVITY';
export const UPDATE_AUTO_SWITCH_PRIVACY = 'UPDATE_AUTO_SWITCH_PRIVACY';
export const UPDATE_TIME_AUTO_SWITCH_PRIVACY = 'UPDATE_TIME_AUTO_SWITCH_PRIVACY';
// Invitees
export const UPDATE_INVITEES = 'UPDATE_INVITEES';
export const UPDATE_INVITED_CIRCLES = 'UPDATE_INVITED_CIRCLES';
export const UPDATE_INVITED_CIRCLES_AND_PRICES = 'UPDATE_INVITED_CIRCLES_AND_PRICES';
export const UDPATE_NOTIFICATION_PREFERENCE_MODE = 'UDPATE_NOTIFICATION_PREFERENCE_MODE';
export const UPDATE_AUTO_NOTIFICATION_TIME = 'UPDATE_AUTO_NOTIFICATION_TIME';
export const NEW_INVITED_CIRCLE = 'NEW_INVITED_CIRCLE';
export const REMOVE_INVITED_CIRCLE = 'REMOVE_INVITED_CIRCLE';
export const NEW_INVITED_CIRCLE_AND_PRICE = 'NEW_INVITED_CIRCLE_AND_PRICE';
export const REMOVE_INVITED_CIRCLE_AND_PRICE = 'REMOVE_INVITED_CIRCLE_AND_PRICE';
export const CLEAR_INVITED_CIRCLES = 'CLEAR_INVITED_CIRCLES';
// main organizer
export const ADD_MAIN_ORGANIZER = 'ADD_MAIN_ORGANIZER';
// Co-Organizers
export const ADD_CO_ORGANIZER = 'ADD_CO_ORGANIZER';
export const REMOVE_CO_ORGANIZER = 'REMOVE_CO_ORGANIZER';
export const RESET_CO_ORGANIZERS = 'RESET_CO_ORGANIZERS';
// Templates
export const UPDATE_SAVE_TEMPLATE_SWITCH = 'UPDATE_SAVE_TEMPLATE_SWITCH';
export const UPDATE_SELECTED_TEMPLATE = 'UPDATE_SELECTED_TEMPLATE';
// loading
export const CHANGE_LOADING_STATUS = 'CHANGE_LOADING_STATUS';
// errors
export const SHOW_NEW_ACTIVITY_ERRORS = 'SHOW_NEW_ACTIVITY_ERRORS';
// reset fields
export const RESET_NEW_ACTIVITY_FIELDS = 'RESET_NEW_ACTIVITY_FIELDS';

export const UPDATE_SPORTS_FORM_VALIDITY = 'UPDATE_SPORTS_FORM_VALIDITY';

// New Circle

export const UPDATE_NEW_CIRCLE_NAME = 'UPDATE_NEW_CIRCLE_NAME';
export const UPDATE_NEW_CIRCLE_DESCRIPTION = 'UPDATE_NEW_CIRCLE_DESCRIPTION';
export const UPDATE_NEW_CIRCLE_PLACE = 'UPDATE_NEW_CIRCLE_PLACE';
export const UPDATE_NEW_CIRCLE_SPORT = 'UPDATE_NEW_CIRCLE_SPORT';
export const UPDATE_NEW_CIRCLE_SPORT_LEVEL = 'UPDATE_NEW_CIRCLE_SPORT_LEVEL';
export const UPDATE_NEW_CIRCLE_TYPE = 'UPDATE_NEW_CIRCLE_TYPE';
export const UPDATE_NEW_CIRCLE_PUBLIC = 'UPDATE_NEW_CIRCLE_PUBLIC';
export const UPDATE_NEW_CIRCLE_ACCESSIBLE_WITH_LINK = 'UPDATE_NEW_CIRCLE_ACCESSIBLE_WITH_LINK';
export const UPDATE_NEW_CIRCLE_SHARED = 'UPDATE_NEW_CIRCLE_SHARED';
export const RESET_NEW_CIRCLE_FIELDS = 'RESET_NEW_CIRCLE_FIELDS';
export const SHOW_NEW_CIRCLE_ERRORS = 'SHOW_NEW_CIRCLE_ERRORS';
export const ADD_CIRCLE_IN_PRIVATE_MODE = 'ADD_CIRCLE_IN_PRIVATE_MODE';
export const REMOVE_CIRCLE_IN_PRIVATE_MODE = 'REMOVE_CIRCLE_IN_PRIVATE_MODE';

// Sortunity

export const STATUS_SPORTUNITY = 'STATUS_SPORTUNITY';
export const IS_PARTICIPANTS_MODAL_VISIBLE = 'IS_PARTICIPANTS_MODAL_VISIBLE';
export const IS_EVENT_LOADING = 'IS_EVENT_LOADING';

// Chat
export const IS_CHAT_MODAL_VISIBLE = 'IS_CHAT_MODAL_VISIBLE';
export const UPDATE_NUM_UNREAD = 'UPDATE_NUM_UNREAD';
export const COUNT_LAST_CHAT = 'COUNT_LAST_CHAT';

// Sportunity List
export const COUNT_SPOTUNITIES = 'COUNT_SPOTUNITIES';

// Locale

export const UPDATE_LOCALE = 'UPDATE_LOCALE';
export const UPDATE_USER_COUNTRY = 'UPDATE_USER_COUNTRY';
export const UPDATE_USER_CURRENCY = 'UPDATE_USER_CURRENCY';
export const UPDATE_USER_LOCATION = 'UPDATE_USER_LOCATION';


// App Notifications Counter
export const PROFILE_NOTIFICATIONS_COUNTS = 'APP_NOTIFICATIONS_COUNTS'


export const UPDATE_CIRCLE_TAB_STATE = 'UPDATE_CIRCLE_TAB_STATE'

// Event Details
export const UPDATE_PARTICIPANT_STATUS = 'UPDATE_PARTICIPANT_STATUS';
export const UPDATE_ORGANISED_STATUS = 'UPDATE_ORGANISED_STATUS';
export const UPDATE_CHAT_ID = 'UPDATE_CHAT_ID';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_SPORTUNITY = 'UPDATE_SPORTUNITY';
export const RESET_SPORTUNITY_DETAILS = 'RESET_SPORTUNITY_DETAILS';
